project_name: ai-fusion-gacode-simulation
namespace: ai-fusion-ga # default (for local testing), ai-fusion-ga (for remote on Nautilus)
user: zclawrence

# uncomment these if you are using a pod and need GPU 
# gpu_count: 1           # 1 or 2 is allowed for an interactive pod
# cpu_count: 16          # optional, keeps the scheduler happy
# memory: 64
# ephemeral_storage: 300

## Image pull related
image: gitlab-registry.nrp-nautilus.io/wesleyliu728/gacode-simulation
tolerations:
  - "nautilus.io/ceph"
## If startup_script is not explicitly specified, the script will automatically pull the latest git repo using ssh_host and ssh_port, and activate the default environment using conda_home and conda_env_name.
# startup_script: . ./.venv/bin/activate

# hostname_whitelist:
#   # - localhost # (for local testing)
#   - gpu-02.csusb.edu
#   - nautilus01.hsrn.nyu.edu
#   # - hcc-nrp-shor-c5226.unl.edu
#   # - hcc-nrp-shor-c5834.unl.edu
#   - hcc-gpn-argo-1.unl.edu
#   # - k8s-4090-01.calit2.optiputer.net
#   - k8s-chase-ci-07.calit2.optiputer.net
#   # - k8s-gen4-sm.calit2.optiputer.net
#   - gpn-fiona-mizzou-4.rnet.missouri.edu
#   - gpn-fiona-mizzou-6.rnet.missouri.edu
#   # - hcc-nrp-shor-c5934.unl.edu
#   - k8s-3090-01.calit2.optiputer.net
#   - knuron.calit2.optiputer.net
#   - prp01.ifa.hawaii.edu
#   - nautilus-ext-gpu01.fullerton.edu
#   - csusb-sci-103-11.csusb.edu
#   - ry-gpu-14.sdsc.optiputer.net
#   - ry-gpu-01.sdsc.optiputer.net
#   - ry-gpu-02.sdsc.optiputer.net
#   - ry-gpu-03.sdsc.optiputer.net
#   - ry-gpu-04.sdsc.optiputer.net
#   - ry-gpu-05.sdsc.optiputer.net
#   - k8s-3090-01.clemson.edu
#   - suncave-12
#   - suncave-14
#   - suncave-2
#   - suncave-8
#   - suncave-9
#   - ry-gpu-06.sdsc.optiputer.net
#   - ry-gpu-08.sdsc.optiputer.net
#   - ry-gpu-12.sdsc.optiputer.net
#   # - ry-gpu-06.sdsc.optiputer.net
#   - k8s-3090-02.clemson.edu
#   # - fiona-1.famu.edu
#   - hcc-chase-shor-c4715.unl.edu
#   - hcc-chase-shor-c4705.unl.edu
#   - hcc-chase-shor-c4709.unl.edu
#   - ry-gpu-04.sdsc.optiputer.net
#   - ry-gpu-10.sdsc.optiputer.net
#   - ry-gpu-07.sdsc.optiputer.net
#   - ry-gpu-09.sdsc.optiputer.net
#   - ry-gpu-11.sdsc.optiputer.net
#   - node-2-1.sdsc.optiputer.net
#   - node-2-2.sdsc.optiputer.net
#   - node-2-4.sdsc.optiputer.net
#   - node-2-3.sdsc.optiputer.net
#   - node-1-2.sdsc.optiputer.net
#   - node-1-4.sdsc.optiputer.net
#   - node-1-1.sdsc.optiputer.net
#   - rci-nrp-gpu-01.sdsu.edu
#   - rci-nrp-gpu-03.sdsu.edu
#   - rci-nrp-gpu-05.sdsu.edu
#   - rci-nrp-gpu-04.sdsu.edu
#   - rci-nrp-gpu-02.sdsu.edu
#   - gp-engine.beocat.ksu.edu
#   - gpengine-uams.areon.net
#   - gpn-fiona-mizzou-2.rnet.missouri.edu
#   - gpn-fiona-mizzou-3.rnet.missouri.edu
#   - gpengine-uark.areon.net
#   - gpn-fiona-mizzou-5.rnet.missouri.edu
#   - discover-nrp-01.sdccd.edu
#   - hcc-prp-c5038.unl.edu
#   - nautilus02.hsrn.nyu.edu
#   - gpu00.nrp.hpc.udel.edu
#   - nrp-01.csumb.edu
#   - k8s-gpu-5.ucsc.edu
#   - tu.gp-engine.greatplains.net
#   # - uicnrp-fiona2.evl.uic.edu
#   - nrp-fiona-001.sdmz.amnh.org

# #2080s
#   - k8s-haosu-16.sdsc.optiputer.net
#   - k8s-haosu-02.sdsc.optiputer.net
#   - k8s-haosu-09.sdsc.optiputer.net
#   - k8s-haosu-18.sdsc.optiputer.net
#   - k8s-gpu-2.ucr.edu
#   - k8s-haosu-03.sdsc.optiputer.net
#   - k8s-haosu-12.sdsc.optiputer.net
#   - nrp-g1.nysernet.org
#   - epic001.clemson.edu
#   - k8s-haosu-20.sdsc.optiputer.net
#   - k8s-haosu-22.sdsc.optiputer.net
#   - fiona-prg1.cesnet.cz
#   - k8s-gpu-3.ucr.edu
#   - k8s-haosu-10.sdsc.optiputer.net
#   - k8s-haosu-11.sdsc.optiputer.net
#   - k8s-haosu-17.sdsc.optiputer.net
#   - k8s-haosu-19.sdsc.optiputer.net
#   - k8s-haosu-04.sdsc.optiputer.net
#   - k8s-haosu-07.sdsc.optiputer.net
#   - k8s-haosu-23.sdsc.optiputer.net
#   - k8s-haosu-06.sdsc.optiputer.net